/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.cadastroUsuarioDAO;
import DTO.cadastroUsuarioDTO;
import VIEW.GerenciarUsuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Arizio
 */
public class atualizacaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form atualizacaoUsuario
     */
    public atualizacaoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenhaAtualiza = new javax.swing.JPasswordField();
        btnAtualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxTipoAtualiza = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtLoginAtualiza = new javax.swing.JTextField();
        txtNomeAtualiza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        MnCadastroCliente = new javax.swing.JMenuItem();
        MnCadastroVeiculo = new javax.swing.JMenuItem();
        MnCadastroUsuario = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MnRelatorioCliente = new javax.swing.JMenuItem();
        MnRelatorioVeiculo = new javax.swing.JMenuItem();
        MnRelatorioUsuario = new javax.swing.JMenuItem();
        MenuAtualizar = new javax.swing.JMenu();
        MnAtualizarCliente = new javax.swing.JMenuItem();
        MnAtualizarVeiculo = new javax.swing.JMenuItem();
        MnAtualizarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Atualização Usuário");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo:");

        cbxTipoAtualiza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionário" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Login:");

        txtLoginAtualiza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNomeAtualiza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAtualizaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("IDUsuario");

        txtIDUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MnCadastro.setText("Cadastro");

        MnCadastroCliente.setText("Cliente");
        MnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroClienteActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroCliente);

        MnCadastroVeiculo.setText("Veículo");
        MnCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroVeiculoActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroVeiculo);

        MnCadastroUsuario.setText("Usuário");
        MnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroUsuarioActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroUsuario);

        jMenuBar1.add(MnCadastro);

        MenuRelatorio.setText("Relatório");

        MnRelatorioCliente.setText("Cliente");
        MnRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioCliente);

        MnRelatorioVeiculo.setText("Veículo");
        MnRelatorioVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioVeiculoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioVeiculo);

        MnRelatorioUsuario.setText("Usuário");
        MnRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioUsuarioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioUsuario);

        jMenuBar1.add(MenuRelatorio);

        MenuAtualizar.setText("Atualizar");

        MnAtualizarCliente.setText("Cliente");
        MnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarClienteActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarCliente);

        MnAtualizarVeiculo.setText("Veículo");
        MnAtualizarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarVeiculoActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarVeiculo);

        MnAtualizarUsuario.setText("Usuário");
        MnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarUsuarioActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarUsuario);

        jMenuBar1.add(MenuAtualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(3, 3, 3)))
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenhaAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(cbxTipoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginAtualiza)
                            .addComponent(txtNomeAtualiza)
                            .addComponent(txtIDUsuario))))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenhaAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addComponent(btnAtualizar)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroClienteActionPerformed
        // Botão do menu para ir a tela cadastroCliente
        cadastroCliente cdCliente = new cadastroCliente();
        this.dispose();
        cdCliente.setVisible(true);
    }//GEN-LAST:event_MnCadastroClienteActionPerformed

    private void MnCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroVeiculoActionPerformed
         // Botão do menu para ir a tela cadastroVeiculo
        cadastroVeiculo cdVeiculo = new cadastroVeiculo();
        this.dispose();
        cdVeiculo.setVisible(true);
    }//GEN-LAST:event_MnCadastroVeiculoActionPerformed

    private void MnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroUsuarioActionPerformed
        // Botão do menu para ir a tela cadastroUsuario
        cadastroUsuario cdUsuario = new cadastroUsuario();
        this.dispose();
        cdUsuario.setVisible(true);
    }//GEN-LAST:event_MnCadastroUsuarioActionPerformed

    private void MnRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioClienteActionPerformed
       // Botão do menu para ir a tela relatorioCliente
        GerenciarCliente rlCliente = new GerenciarCliente();
        this.dispose();
        rlCliente.setVisible(true);
    }//GEN-LAST:event_MnRelatorioClienteActionPerformed

    private void MnRelatorioVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioVeiculoActionPerformed
        // Botão do menu para ir a tela relatorioVeiculo
        GerenciarVeiculo rlVeiculo = new GerenciarVeiculo();
        this.dispose();
        rlVeiculo.setVisible(true);
    }//GEN-LAST:event_MnRelatorioVeiculoActionPerformed

    private void MnRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioUsuarioActionPerformed
         // Botão do menu para ir a tela relatorioUsuario
        GerenciarUsuario rlUsuario = new GerenciarUsuario();
        this.dispose();
        rlUsuario.setVisible(true);
    }//GEN-LAST:event_MnRelatorioUsuarioActionPerformed

    private void MnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarClienteActionPerformed
       // Botão do menu para ir a tela atualizarCliente
        atualizacaoCliente atCliente = new atualizacaoCliente();
        this.dispose();
        atCliente.setVisible(true);
    }//GEN-LAST:event_MnAtualizarClienteActionPerformed

    private void MnAtualizarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarVeiculoActionPerformed
         // Botão do menu para ir a tela atualizarVeiculo
        atualizacaoVeiculo atVeiculo = new atualizacaoVeiculo();
        this.dispose();
        atVeiculo.setVisible(true);
    }//GEN-LAST:event_MnAtualizarVeiculoActionPerformed

    private void MnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarUsuarioActionPerformed
       // Botão do menu para ir a tela atualizarUsuario
        atualizacaoUsuario atUsuario = new atualizacaoUsuario();
        this.dispose();
        atUsuario.setVisible(true);
    }//GEN-LAST:event_MnAtualizarUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        povoarJTable();
    }//GEN-LAST:event_formWindowOpened

    private void txtNomeAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAtualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAtualizaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // Pega os dados dos componentes e armazena no cadastroUsuarioDTO
        atualizaUsuario();
        
        //Chama o método para limpar os campos
        limparCampos();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atualizacaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAtualizar;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MnAtualizarCliente;
    private javax.swing.JMenuItem MnAtualizarUsuario;
    private javax.swing.JMenuItem MnAtualizarVeiculo;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuItem MnCadastroCliente;
    private javax.swing.JMenuItem MnCadastroUsuario;
    private javax.swing.JMenuItem MnCadastroVeiculo;
    private javax.swing.JMenuItem MnRelatorioCliente;
    private javax.swing.JMenuItem MnRelatorioUsuario;
    private javax.swing.JMenuItem MnRelatorioVeiculo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox<String> cbxTipoAtualiza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtLoginAtualiza;
    private javax.swing.JTextField txtNomeAtualiza;
    private javax.swing.JPasswordField txtSenhaAtualiza;
    // End of variables declaration//GEN-END:variables
   
    //método para atualizar o usuario coletando os dados da tela e setando novos dados no banco
    private void atualizaUsuario() {
        String idUsuario, NomeUsuarioCadastro, loginUsuarioCadastro, senhaUsuarioCadastro, Tipo;

        idUsuario = txtIDUsuario.getText();
        NomeUsuarioCadastro = txtNomeAtualiza.getText();
        loginUsuarioCadastro = txtLoginAtualiza.getText();
        senhaUsuarioCadastro = String.valueOf(txtSenhaAtualiza.getPassword());
        Tipo = cbxTipoAtualiza.getSelectedItem().toString();

        cadastroUsuarioDTO objAtualizaUsuarioDTO = new cadastroUsuarioDTO();

        objAtualizaUsuarioDTO.setIdUsuario(idUsuario);
        objAtualizaUsuarioDTO.setLoginUsuarioCadastro(loginUsuarioCadastro);
        objAtualizaUsuarioDTO.setNomeUsuarioCadastro(NomeUsuarioCadastro);
        objAtualizaUsuarioDTO.setSenhaUsuarioCadastro(senhaUsuarioCadastro);
        objAtualizaUsuarioDTO.setTipo(Tipo);

        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");

    }

    // método para povoar as caixas de texto com informações das quais desejo alterar
    public void povoarJTable() {
        Connection conn;

        ResultSet rs;

        PreparedStatement pstm;

        conn = new ConexaoDAO().conectaBD(); //conectar ao banco

        String sql = "SELECT * FROM cadastroUsuario WHERE idUsuario = '" + cadastroUsuarioDTO.idUsuario + "'";

        try {
            pstm = conn.prepareStatement(sql);
            pstm.execute();

            rs = pstm.executeQuery();

            rs.next();

            txtIDUsuario.setText(rs.getString("idUsuario"));
            txtNomeAtualiza.setText(rs.getString("Nome"));
            txtLoginAtualiza.setText(rs.getString("Login"));
            txtSenhaAtualiza.setText(rs.getString("Senha"));
            cbxTipoAtualiza.setSelectedItem(rs.getString("Tipo"));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar no banco de dados! Erro:" + e);
        }
    }

    private void limparCampos() {
        txtIDUsuario.setText("");
        txtLoginAtualiza.setText("");
        txtNomeAtualiza.setText("");
        txtSenhaAtualiza.setText("");
        cbxTipoAtualiza.setSelectedItem("");
    }

}

