/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.cadastroUsuarioDAO;
import DTO.cadastroUsuarioDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Arizio
 */
public class GerenciarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form relatorioUsuario
     */
    public GerenciarUsuario() {
        initComponents();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtNomeResult = new javax.swing.JTextField();
        cbxTipoPesquisa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorioUsuario = new javax.swing.JTable();
        txtLoginPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        MnCadastroCliente = new javax.swing.JMenuItem();
        MnCadastroVeiculo = new javax.swing.JMenuItem();
        MnCadastroUsuario = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MnRelatorioCliente = new javax.swing.JMenuItem();
        MnRelatorioVeiculo = new javax.swing.JMenuItem();
        MnRelatorioUsuario = new javax.swing.JMenuItem();
        MenuAtualizar = new javax.swing.JMenu();
        MnAtualizarCliente = new javax.swing.JMenuItem();
        MnAtualizarVeiculo = new javax.swing.JMenuItem();
        MnAtualizarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtNomeResult.setEditable(false);
        txtNomeResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeResultActionPerformed(evt);
            }
        });

        cbxTipoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Funcionário", "Administrador" }));
        cbxTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPesquisaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de Usuários");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Login:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        tblRelatorioUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Usuario", "Nome", "Login", "Senha", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelatorioUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblRelatorioUsuarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblRelatorioUsuario);
        if (tblRelatorioUsuario.getColumnModel().getColumnCount() > 0) {
            tblRelatorioUsuario.getColumnModel().getColumn(0).setMinWidth(60);
            tblRelatorioUsuario.getColumnModel().getColumn(0).setMaxWidth(60);
            tblRelatorioUsuario.getColumnModel().getColumn(1).setMinWidth(140);
            tblRelatorioUsuario.getColumnModel().getColumn(1).setMaxWidth(140);
        }

        txtLoginPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLoginPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPesquisaActionPerformed(evt);
            }
        });
        txtLoginPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginPesquisaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Usuario Selecionado:");

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Código:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        MnCadastro.setText("Cadastro");

        MnCadastroCliente.setText("Cliente");
        MnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroClienteActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroCliente);

        MnCadastroVeiculo.setText("Veículo");
        MnCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroVeiculoActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroVeiculo);

        MnCadastroUsuario.setText("Usuário");
        MnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroUsuarioActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroUsuario);

        jMenuBar1.add(MnCadastro);

        MenuRelatorio.setText("Relatório");

        MnRelatorioCliente.setText("Cliente");
        MnRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioCliente);

        MnRelatorioVeiculo.setText("Veículo");
        MnRelatorioVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioVeiculoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioVeiculo);

        MnRelatorioUsuario.setText("Usuário");
        MnRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioUsuarioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioUsuario);

        jMenuBar1.add(MenuRelatorio);

        MenuAtualizar.setText("Atualizar");

        MnAtualizarCliente.setText("Cliente");
        MnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarClienteActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarCliente);

        MnAtualizarVeiculo.setText("Veículo");
        MnAtualizarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarVeiculoActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarVeiculo);

        MnAtualizarUsuario.setText("Usuário");
        MnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarUsuarioActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarUsuario);

        jMenuBar1.add(MenuAtualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtLoginPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(cbxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnLimparCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(390, 390, 390)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(cbxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(69, 69, 69)
                        .addComponent(btnLimparCampos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroClienteActionPerformed
        // Botão do menu para ir a tela cadastroCliente
        cadastroCliente cdCliente = new cadastroCliente();
        this.dispose();
        cdCliente.setVisible(true);
    }//GEN-LAST:event_MnCadastroClienteActionPerformed

    private void MnCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroVeiculoActionPerformed
        // Botão do menu para ir a tela cadastroVeiculo
        cadastroVeiculo cdVeiculo = new cadastroVeiculo();
        this.dispose();
        cdVeiculo.setVisible(true);
    }//GEN-LAST:event_MnCadastroVeiculoActionPerformed

    private void MnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroUsuarioActionPerformed
        // Botão do menu para ir a tela cadastroUsuario
        cadastroUsuario cdUsuario = new cadastroUsuario();
        this.dispose();
        cdUsuario.setVisible(true);
    }//GEN-LAST:event_MnCadastroUsuarioActionPerformed

    private void MnRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioClienteActionPerformed
        // Botão do menu para ir a tela relatorioCliente
        GerenciarCliente rlCliente = new GerenciarCliente();
        this.dispose();
        rlCliente.setVisible(true);
    }//GEN-LAST:event_MnRelatorioClienteActionPerformed

    private void MnRelatorioVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioVeiculoActionPerformed
        // Botão do menu para ir a tela relatorioVeiculo
        GerenciarVeiculo rlVeiculo = new GerenciarVeiculo();
        this.dispose();
        rlVeiculo.setVisible(true);
    }//GEN-LAST:event_MnRelatorioVeiculoActionPerformed

    private void MnRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioUsuarioActionPerformed
        // Botão do menu para ir a tela relatorioUsuario
        GerenciarUsuario rlUsuario = new GerenciarUsuario();
        this.dispose();
        rlUsuario.setVisible(true);
    }//GEN-LAST:event_MnRelatorioUsuarioActionPerformed

    private void MnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarClienteActionPerformed
        // Botão do menu para ir a tela atualizarCliente
        atualizacaoCliente atCliente = new atualizacaoCliente();
        this.dispose();
        atCliente.setVisible(true);
    }//GEN-LAST:event_MnAtualizarClienteActionPerformed

    private void MnAtualizarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarVeiculoActionPerformed
        // Botão do menu para ir a tela atualizarVeiculo
        atualizacaoVeiculo atVeiculo = new atualizacaoVeiculo();
        this.dispose();
        atVeiculo.setVisible(true);
    }//GEN-LAST:event_MnAtualizarVeiculoActionPerformed

    private void MnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarUsuarioActionPerformed
        // Botão do menu para ir a tela atualizarUsuario
        atualizacaoUsuario atUsuario = new atualizacaoUsuario();
        this.dispose();
        atUsuario.setVisible(true);
    }//GEN-LAST:event_MnAtualizarUsuarioActionPerformed

    private void txtLoginPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginPesquisaKeyReleased
        // Chamar método para pesquisar através do nome
        pesquisarLogin();
    }//GEN-LAST:event_txtLoginPesquisaKeyReleased

    private void cbxTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPesquisaActionPerformed
        // Chama o método pesquisarLoginCBX
        pesquisarLogin();
        
    }//GEN-LAST:event_cbxTipoPesquisaActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // Chama um método para limpar um nome do campo de texto
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtNomeResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeResultActionPerformed

    private void tblRelatorioUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelatorioUsuarioMouseReleased
        // Chamando Variavel para carregar o campo com o nome do cliente
        carregarCampos();
    }//GEN-LAST:event_tblRelatorioUsuarioMouseReleased

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        atualizacaoUsuario atUsuario = new atualizacaoUsuario();
        this.dispose();
        atUsuario.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtLoginPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPesquisaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluiUsuarios();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAtualizar;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MnAtualizarCliente;
    private javax.swing.JMenuItem MnAtualizarUsuario;
    private javax.swing.JMenuItem MnAtualizarVeiculo;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuItem MnCadastroCliente;
    private javax.swing.JMenuItem MnCadastroUsuario;
    private javax.swing.JMenuItem MnCadastroVeiculo;
    private javax.swing.JMenuItem MnRelatorioCliente;
    private javax.swing.JMenuItem MnRelatorioUsuario;
    private javax.swing.JMenuItem MnRelatorioVeiculo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JComboBox<String> cbxTipoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRelatorioUsuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLoginPesquisa;
    private javax.swing.JTextField txtNomeResult;
    // End of variables declaration//GEN-END:variables

    //Método para Listar os Usuarios
    private void listarUsuarios() {

        try {

            cadastroUsuarioDAO objcadastroUsuarioDAO = new cadastroUsuarioDAO();

            DefaultTableModel model = (DefaultTableModel) tblRelatorioUsuario.getModel();
            model.setNumRows(0);

            ArrayList<cadastroUsuarioDTO> lista = objcadastroUsuarioDAO.listarUsuario();

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getIdUsuario(),
                    lista.get(i).getNomeUsuarioCadastro(),
                    lista.get(i).getLoginUsuarioCadastro(),
                    lista.get(i).getSenhaUsuarioCadastro(),
                    lista.get(i).getTipo()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Usuarios VIEW: " + erro);
        }
    }
    
     //método para deletar os Usuarios
    private void excluiUsuarios(){
        String idUsuario;
        
        idUsuario = txtCodigo.getText();
        
        cadastroUsuarioDTO objDeletaUsuarioDTO = new cadastroUsuarioDTO();
        objDeletaUsuarioDTO.setIdUsuario(idUsuario);
        
        cadastroUsuarioDAO objExcluirUsuarioDAO = new cadastroUsuarioDAO();
        objExcluirUsuarioDAO.excluirUsuario(objDeletaUsuarioDTO);
    }
    
    //  Método para pesquisar pelo login do usuario
    private void pesquisarLogin(){
        DefaultTableModel ob = (DefaultTableModel) tblRelatorioUsuario.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tblRelatorioUsuario.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txtLoginPesquisa.getText()));
        
        // if else para a combobox
        if (cbxTipoPesquisa.getSelectedItem().toString() == "Todos"){
        listarUsuarios();
        }else{     
        tblRelatorioUsuario.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(cbxTipoPesquisa.getSelectedItem().toString()));
        }
    }
    
    public void carregarCampos(){
        int setar = tblRelatorioUsuario.getSelectedRow();
        
        txtCodigo.setText(tblRelatorioUsuario.getModel().getValueAt(setar, 0).toString());
        txtNomeResult.setText(tblRelatorioUsuario.getModel().getValueAt(setar, 1).toString());   
        txtLoginPesquisa.setText(tblRelatorioUsuario.getModel().getValueAt(setar, 2).toString());             
    }
    
    
    private void limparCampos() {
        txtNomeResult.setText("");
        txtLoginPesquisa.setText("");
        cbxTipoPesquisa.setSelectedItem("Todos");
        txtCodigo.setText("");
    }

}
