/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.cadastroVeiculoDAO;
import DTO.cadastroVeiculoDTO;
import VIEW.GerenciarUsuario;
import VIEW.GerenciarCliente;
import VIEW.cadastroVeiculo;
import VIEW.cadastroUsuario;
import VIEW.cadastroCliente;
import VIEW.atualizacaoVeiculo;
import VIEW.atualizacaoUsuario;
import VIEW.atualizacaoCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Arizio
 */
public class GerenciarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form relatorioVeiculo
     */
    public GerenciarVeiculo() {
        initComponents();
        listarVeiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModeloPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorioVeiculo = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPlacaPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        MnCadastroCliente = new javax.swing.JMenuItem();
        MnCadastroVeiculo = new javax.swing.JMenuItem();
        MnCadastroUsuario = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MnRelatorioCliente = new javax.swing.JMenuItem();
        MnRelatorioVeiculo = new javax.swing.JMenuItem();
        MnRelatorioUsuario = new javax.swing.JMenuItem();
        MenuAtualizar = new javax.swing.JMenu();
        MnAtualizarCliente = new javax.swing.JMenuItem();
        MnAtualizarVeiculo = new javax.swing.JMenuItem();
        MnAtualizarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de Veículos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        txtModeloPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtModeloPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModeloPesquisarKeyReleased(evt);
            }
        });

        tblRelatorioVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Ano", "CPF"
            }
        ));
        tblRelatorioVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblRelatorioVeiculoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblRelatorioVeiculo);
        if (tblRelatorioVeiculo.getColumnModel().getColumnCount() > 0) {
            tblRelatorioVeiculo.getColumnModel().getColumn(0).setMinWidth(100);
            tblRelatorioVeiculo.getColumnModel().getColumn(0).setMaxWidth(100);
            tblRelatorioVeiculo.getColumnModel().getColumn(3).setMinWidth(70);
            tblRelatorioVeiculo.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPlacaPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlacaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaPesquisarActionPerformed(evt);
            }
        });
        txtPlacaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaPesquisarKeyReleased(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Placa Selecionado:");

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Veiculo Selecionado:");

        txtModelo.setEditable(false);
        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MnCadastro.setText("Cadastro");

        MnCadastroCliente.setText("Cliente");
        MnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroClienteActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroCliente);

        MnCadastroVeiculo.setText("Veículo");
        MnCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroVeiculoActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroVeiculo);

        MnCadastroUsuario.setText("Usuário");
        MnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroUsuarioActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroUsuario);

        jMenuBar1.add(MnCadastro);

        MenuRelatorio.setText("Gerenciar");

        MnRelatorioCliente.setText("Cliente");
        MnRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioCliente);

        MnRelatorioVeiculo.setText("Veículo");
        MnRelatorioVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioVeiculoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioVeiculo);

        MnRelatorioUsuario.setText("Usuário");
        MnRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioUsuarioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioUsuario);

        jMenuBar1.add(MenuRelatorio);

        MenuAtualizar.setText("Atualizar");

        MnAtualizarCliente.setText("Cliente");
        MnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarClienteActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarCliente);

        MnAtualizarVeiculo.setText("Veículo");
        MnAtualizarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarVeiculoActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarVeiculo);

        MnAtualizarUsuario.setText("Usuário");
        MnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarUsuarioActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarUsuario);

        jMenuBar1.add(MenuAtualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlacaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtModeloPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLimparCampos)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(316, 316, 316)
                                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPlacaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtModeloPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar))))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(21, 21, 21)
                .addComponent(btnLimparCampos)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroClienteActionPerformed
        // Botão do menu para ir a tela cadastroCliente
        cadastroCliente cdCliente = new cadastroCliente();
        this.dispose();
        cdCliente.setVisible(true);
    }//GEN-LAST:event_MnCadastroClienteActionPerformed

    private void MnCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroVeiculoActionPerformed
        // Botão do menu para ir a tela cadastroVeiculo
        cadastroVeiculo cdVeiculo = new cadastroVeiculo();
        this.dispose();
        cdVeiculo.setVisible(true);
    }//GEN-LAST:event_MnCadastroVeiculoActionPerformed

    private void MnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroUsuarioActionPerformed
        // Botão do menu para ir a tela cadastroUsuario
        cadastroUsuario cdUsuario = new cadastroUsuario();
        this.dispose();
        cdUsuario.setVisible(true);
    }//GEN-LAST:event_MnCadastroUsuarioActionPerformed

    private void MnRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioClienteActionPerformed
        // Botão do menu para ir a tela relatorioCliente
        GerenciarCliente rlCliente = new GerenciarCliente();
        this.dispose();
        rlCliente.setVisible(true);
    }//GEN-LAST:event_MnRelatorioClienteActionPerformed

    private void MnRelatorioVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioVeiculoActionPerformed
        // Botão do menu para ir a tela relatorioVeiculo
        GerenciarVeiculo rlVeiculo = new GerenciarVeiculo();
        this.dispose();
        rlVeiculo.setVisible(true);
    }//GEN-LAST:event_MnRelatorioVeiculoActionPerformed

    private void MnRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioUsuarioActionPerformed
       // Botão do menu para ir a tela relatorioUsuario
        GerenciarUsuario rlUsuario = new GerenciarUsuario();
        this.dispose();
        rlUsuario.setVisible(true);
    }//GEN-LAST:event_MnRelatorioUsuarioActionPerformed

    private void MnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarClienteActionPerformed
        // Botão do menu para ir a tela atualizarCliente
        atualizacaoCliente atCliente = new atualizacaoCliente();
        this.dispose();
        atCliente.setVisible(true);
    }//GEN-LAST:event_MnAtualizarClienteActionPerformed

    private void MnAtualizarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarVeiculoActionPerformed
       // Botão do menu para ir a tela atualizarVeiculo
        atualizacaoVeiculo atVeiculo = new atualizacaoVeiculo();
        this.dispose();
        atVeiculo.setVisible(true);
    }//GEN-LAST:event_MnAtualizarVeiculoActionPerformed

    private void MnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarUsuarioActionPerformed
        // Botão do menu para ir a tela atualizarUsuario
        atualizacaoUsuario atUsuario = new atualizacaoUsuario();
        this.dispose();
        atUsuario.setVisible(true);
    }//GEN-LAST:event_MnAtualizarUsuarioActionPerformed

    private void txtPlacaPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarPlaca();
    }//GEN-LAST:event_txtPlacaPesquisarKeyReleased

    private void txtModeloPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarPlaca();
    }//GEN-LAST:event_txtModeloPesquisarKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        atualizacaoVeiculo atVeiculo = new atualizacaoVeiculo();
        this.dispose();
        atVeiculo.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Chama método para excluir dados
        excluiVeiculo();
        listarVeiculo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblRelatorioVeiculoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelatorioVeiculoMouseReleased
        // TODO add your handling code here:
        carregarCampos();
    }//GEN-LAST:event_tblRelatorioVeiculoMouseReleased

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void txtPlacaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAtualizar;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MnAtualizarCliente;
    private javax.swing.JMenuItem MnAtualizarUsuario;
    private javax.swing.JMenuItem MnAtualizarVeiculo;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuItem MnCadastroCliente;
    private javax.swing.JMenuItem MnCadastroUsuario;
    private javax.swing.JMenuItem MnCadastroVeiculo;
    private javax.swing.JMenuItem MnRelatorioCliente;
    private javax.swing.JMenuItem MnRelatorioUsuario;
    private javax.swing.JMenuItem MnRelatorioVeiculo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRelatorioVeiculo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModeloPesquisar;
    private javax.swing.JTextField txtPlacaPesquisar;
    // End of variables declaration//GEN-END:variables

     private void listarVeiculo() {

        try {

            cadastroVeiculoDAO objcadastroveiculoDAO = new cadastroVeiculoDAO();

            DefaultTableModel model = (DefaultTableModel) tblRelatorioVeiculo.getModel();
            model.setNumRows(0);

            ArrayList<cadastroVeiculoDTO> lista = objcadastroveiculoDAO.listarVeiculo();

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getPlaca(),
                    lista.get(i).getMarca(),
                    lista.get(i).getModelo(),
                    lista.get(i).getAno(),
                    lista.get(i).getIdCPF(),
                    lista.get(i).getNome()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Usuarios VIEW: " + erro);
        }
    }
    //método para deletar os clientes
    private void excluiVeiculo(){
        String idPlaca;
        
        idPlaca = txtCodigo.getText();
        
        cadastroVeiculoDTO objDeletaClienteDTO = new cadastroVeiculoDTO();
        objDeletaClienteDTO.setIdCPF(idPlaca);
        
        cadastroVeiculoDAO objExcluirVeiculoDAO = new cadastroVeiculoDAO();
        objExcluirVeiculoDAO.excluirVeiculo(objDeletaClienteDTO);
    }
    //pesquisar pela placa ou modelo
     
private void pesquisarPlaca(){
        DefaultTableModel ob = (DefaultTableModel) tblRelatorioVeiculo.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tblRelatorioVeiculo.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txtPlacaPesquisar.getText()));
        obj.setRowFilter(RowFilter.regexFilter(txtModeloPesquisar.getText()));
    }

public void carregarCampos(){
        int setar = tblRelatorioVeiculo.getSelectedRow();
        
        txtCodigo.setText(tblRelatorioVeiculo.getModel().getValueAt(setar, 0).toString());
        txtModeloPesquisar.setText(tblRelatorioVeiculo.getModel().getValueAt(setar, 2).toString());   
         txtModelo.setText(tblRelatorioVeiculo.getModel().getValueAt(setar, 2).toString());
        txtPlacaPesquisar.setText(tblRelatorioVeiculo.getModel().getValueAt(setar, 0).toString());             
    }

 private void limparCampos() {
        txtCodigo.setText("");
        txtModeloPesquisar.setText("");
        txtPlacaPesquisar.setText("");
        txtModelo.setText("");
        
    }
        
}
