/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.CadastroClienteDAO;
import DTO.cadastroClienteDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Arizio
 */
public class GerenciarCliente extends javax.swing.JFrame {

    /**
     * Creates new form relatorioCliente
     */
    public GerenciarCliente() {
        initComponents();
        listarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnomePesquisar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRelatorioCliente = new javax.swing.JTable();
        btnExcluirCliente = new javax.swing.JButton();
        btnAtualiza = new javax.swing.JButton();
        txtNomeResult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        MnCadastroCliente = new javax.swing.JMenuItem();
        MnCadastroVeiculo = new javax.swing.JMenuItem();
        MnCadastroUsuario = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MnRelatorioCliente = new javax.swing.JMenuItem();
        MnRelatorioVeiculo = new javax.swing.JMenuItem();
        MnRelatorioUsuario = new javax.swing.JMenuItem();
        MenuAtualizar = new javax.swing.JMenu();
        MnAtualizarCliente = new javax.swing.JMenuItem();
        MnAtualizarVeiculo = new javax.swing.JMenuItem();
        MnAtualizarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de Clientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite o Nome ou o CPF:");

        txtnomePesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnomePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomePesquisarActionPerformed(evt);
            }
        });
        txtnomePesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomePesquisarKeyReleased(evt);
            }
        });

        tblRelatorioCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblRelatorioCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {"", "", "", "", ""},
                {"", null, "", "", ""},
                {"", "", "", "", ""},
                {"", "", "", "", ""},
                {"", null, "", "", ""},
                {"", "", "", "", ""},
                {"", null, "", "", ""},
                {"", null, "", "", ""},
                {"", "", "", "", ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Email", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelatorioCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblRelatorioCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblRelatorioClienteMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblRelatorioCliente);
        if (tblRelatorioCliente.getColumnModel().getColumnCount() > 0) {
            tblRelatorioCliente.getColumnModel().getColumn(0).setMinWidth(120);
            tblRelatorioCliente.getColumnModel().getColumn(0).setMaxWidth(120);
            tblRelatorioCliente.getColumnModel().getColumn(1).setMinWidth(150);
            tblRelatorioCliente.getColumnModel().getColumn(1).setMaxWidth(150);
            tblRelatorioCliente.getColumnModel().getColumn(2).setMinWidth(150);
            tblRelatorioCliente.getColumnModel().getColumn(2).setMaxWidth(150);
            tblRelatorioCliente.getColumnModel().getColumn(3).setMinWidth(150);
            tblRelatorioCliente.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        btnExcluirCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnAtualiza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualiza.setText("Atualizar");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        txtNomeResult.setEditable(false);
        txtNomeResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeResultActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Cliente Selecionado:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Limpar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("CPF:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        MnCadastro.setText("Cadastro");

        MnCadastroCliente.setText("Cliente");
        MnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroClienteActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroCliente);

        MnCadastroVeiculo.setText("Veículo");
        MnCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroVeiculoActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroVeiculo);

        MnCadastroUsuario.setText("Usuário");
        MnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCadastroUsuarioActionPerformed(evt);
            }
        });
        MnCadastro.add(MnCadastroUsuario);

        jMenuBar1.add(MnCadastro);

        MenuRelatorio.setText("Gerenciar");

        MnRelatorioCliente.setText("Cliente");
        MnRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioCliente);

        MnRelatorioVeiculo.setText("Veículo");
        MnRelatorioVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioVeiculoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioVeiculo);

        MnRelatorioUsuario.setText("Usuário");
        MnRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelatorioUsuarioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MnRelatorioUsuario);

        jMenuBar1.add(MenuRelatorio);

        MenuAtualizar.setText("Atualizar");

        MnAtualizarCliente.setText("Cliente");
        MnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarClienteActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarCliente);

        MnAtualizarVeiculo.setText("Veículo");
        MnAtualizarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarVeiculoActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarVeiculo);

        MnAtualizarUsuario.setText("Usuário");
        MnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAtualizarUsuarioActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MnAtualizarUsuario);

        jMenuBar1.add(MenuAtualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNomeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtnomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtnomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNomeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAtualiza)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirCliente)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroClienteActionPerformed
        // Botão do menu para ir a tela cadastroVeiculo
        cadastroCliente cdCliente = new cadastroCliente();
        this.dispose();
        cdCliente.setVisible(true);
    }//GEN-LAST:event_MnCadastroClienteActionPerformed

    private void MnCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroVeiculoActionPerformed
        // Botão do menu para ir a tela cadastroVeiculo
        cadastroVeiculo cdVeiculo = new cadastroVeiculo();
        this.dispose();
        cdVeiculo.setVisible(true);
    }//GEN-LAST:event_MnCadastroVeiculoActionPerformed

    private void MnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCadastroUsuarioActionPerformed
        // Botão do menu para ir a tela cadastroUsuario
        cadastroUsuario cdUsuario = new cadastroUsuario();
        this.dispose();
        cdUsuario.setVisible(true);
    }//GEN-LAST:event_MnCadastroUsuarioActionPerformed

    private void MnRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioClienteActionPerformed
        // Botão do menu para ir a tela relatorioCliente
        GerenciarCliente rlCliente = new GerenciarCliente();
        this.dispose();
        rlCliente.setVisible(true);
    }//GEN-LAST:event_MnRelatorioClienteActionPerformed

    private void MnRelatorioVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioVeiculoActionPerformed
        // Botão do menu para ir a tela relatorioVeiculo
        GerenciarVeiculo rlVeiculo = new GerenciarVeiculo();
        this.dispose();
        rlVeiculo.setVisible(true);
    }//GEN-LAST:event_MnRelatorioVeiculoActionPerformed

    private void MnRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelatorioUsuarioActionPerformed
        // Botão do menu para ir a tela relatorioUsuario
        GerenciarUsuario rlUsuario = new GerenciarUsuario();
        this.dispose();
        rlUsuario.setVisible(true);
    }//GEN-LAST:event_MnRelatorioUsuarioActionPerformed

    private void MnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarClienteActionPerformed
        // Botão do menu para ir a tela atualizarCliente
        atualizacaoCliente atCliente = new atualizacaoCliente();
        this.dispose();
        atCliente.setVisible(true);
    }//GEN-LAST:event_MnAtualizarClienteActionPerformed

    private void MnAtualizarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarVeiculoActionPerformed
        // Botão do menu para ir a tela atualizarVeiculo
        atualizacaoVeiculo atVeiculo = new atualizacaoVeiculo();
        this.dispose();
        atVeiculo.setVisible(true);
    }//GEN-LAST:event_MnAtualizarVeiculoActionPerformed

    private void MnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAtualizarUsuarioActionPerformed
        // Botão do menu para ir a tela atualizarUsuario
        atualizacaoUsuario atUsuario = new atualizacaoUsuario();
        this.dispose();
        atUsuario.setVisible(true);
    }//GEN-LAST:event_MnAtualizarUsuarioActionPerformed

    private void txtnomePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomePesquisarActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_txtnomePesquisarActionPerformed

    private void txtnomePesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomePesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarNome();
    }//GEN-LAST:event_txtnomePesquisarKeyReleased

    private void txtNomeResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeResultActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        // TODO add your handling code here:
        atualizacaoCliente atCliente = new atualizacaoCliente();
        this.dispose();
        atCliente.setVisible(true);
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void tblRelatorioClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelatorioClienteMouseReleased
        // TODO add your handling code here:
        carregarCampos();
    }//GEN-LAST:event_tblRelatorioClienteMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        ExcluiClientes();
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAtualizar;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MnAtualizarCliente;
    private javax.swing.JMenuItem MnAtualizarUsuario;
    private javax.swing.JMenuItem MnAtualizarVeiculo;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuItem MnCadastroCliente;
    private javax.swing.JMenuItem MnCadastroUsuario;
    private javax.swing.JMenuItem MnCadastroVeiculo;
    private javax.swing.JMenuItem MnRelatorioCliente;
    private javax.swing.JMenuItem MnRelatorioUsuario;
    private javax.swing.JMenuItem MnRelatorioVeiculo;
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblRelatorioCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeResult;
    private javax.swing.JTextField txtnomePesquisar;
    // End of variables declaration//GEN-END:variables

    //método para listar os clientes
    private void listarCliente() {

        try {

            CadastroClienteDAO objcadastroClienteDAO = new CadastroClienteDAO();

            DefaultTableModel model = (DefaultTableModel) tblRelatorioCliente.getModel();
            model.setNumRows(0);

            ArrayList<cadastroClienteDTO> lista = objcadastroClienteDAO.listarCliente();
            

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getIdCPF(),
                    lista.get(i).getNome(),
                    lista.get(i).getTel(),
                    lista.get(i).getEmail(),
                    lista.get(i).getEndereco()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Usuarios VIEW: " + erro);
        }
    }
    
    //método para deletar os clientes
    private void ExcluiClientes(){
        String idCPF;
        
        idCPF = txtCodigo.getText();
        
        cadastroClienteDTO objDeletaClienteDTO = new cadastroClienteDTO();
        objDeletaClienteDTO.setIdCPF(idCPF);
        
        CadastroClienteDAO objExcluirClienteDAO = new CadastroClienteDAO();
        objExcluirClienteDAO.excluirCliente(objDeletaClienteDTO);
    }

    //método para pesquisar nome pelo textfield
    private void pesquisarNome() {
        DefaultTableModel ob = (DefaultTableModel) tblRelatorioCliente.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tblRelatorioCliente.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txtnomePesquisar.getText()));
    }

    //método para pesquisar o nome pelo textfield
    public void carregarCampos() {
        int setar = tblRelatorioCliente.getSelectedRow();

        txtNomeResult.setText(tblRelatorioCliente.getModel().getValueAt(setar, 1).toString());
        txtCodigo.setText(tblRelatorioCliente.getModel().getValueAt(setar, 0).toString());
    }
    private void limparCampos(){
    txtNomeResult.setText("");
    txtCodigo.setText("");
    txtnomePesquisar.setText("");
}
}
